[book]
title = "The Redox Operating System"
author = "The RedoxOS Developers"
description = "This book carefully describes the design, implementation, direction, and structure of Redox, the operating system."
multilingual = false
src = "src"

[output.html]
theme = "./theme"

[output.linkcheck]
# web links can spuriously fail on CI
follow-web-links = false

